### ISSUE TITLE
checkedInObservable in checkin services undefined.

### ISSUE THREAD

**Issue by cmcginn** [skeary/QRCheckIn#1]
In qr_checkin_service.js
you have defined a checkInTicket function with the following signature.
 this.checkInTicket = function(endpointUrl, apiKey, event, ticketToken, lastCheckInResultModel, checkedInObservable)

This method gets called in scan_vm, however the checkedInObservable is never passed as an argument. 

self.server.checkInTicket(
            self.settingsPageViewModel.endpoint(),
            self.settingsPageViewModel.apiKey(),
            self.settingsPageViewModel.selectedEvent(),
            ticketToken,
            self.lastCheckInResultModel
          );
The success event 
 function (isSuccessful) {
if (isSuccessful) {
checkedInObservable(true);
} 

Subsequently fails.

Am I missing something, or is it safe to comment out? What should this "checkedInObservable(true);" do?

Regards

![bug](https://f.cloud.github.com/assets/726671/986056/ce2c32ec-08d0-11e3-81ee-156625fa6dc3.jpg)

**Comment by skeary** [comment]
Hi Chris,

The checkedInObservable argument is not passed in for the call in ScanViewModel.scanAndCheckInTicket() but it is passed in for the call in SearchPageViewModel.checkInTicket(). This allows QRCheckInServices.checkInTicket() to return the checked in/out status to the caller via an observable. The observable is used on the search page to sync the checked in toggle buttons with the actual checked in/out state from the server. (See search page screenshot on https://itunes.apple.com/ag/app/qr-check-in/id645943977?mt=8 for what I mean).

It does look like there will be an error when the checkInTicket() function is called via ScanViewModel as the argument will be null. I think the best course of action is to put a guard around the call:

```
          if (isSuccessful && checkedInObservable != null) {
            checkedInObservable(true);
          }
```

The same should also be done in checkOutTicket().

Thanks for pointing this out. I'll hopefully update the code, test it and push in the next few days.

Simon

**Comment by cmcginn** [comment]
Thanks very much, will go ahead and do that.

Date: Mon, 19 Aug 2013 07:29:24 -0700
